# -*- coding: utf-8 -*-
"""Decision_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mESpAf5vVIjFaFl8mRhRbjYI2dOr9_T
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/salaries (1).csv')
df

inputs = df.drop('salary_more_then_100k',axis='columns')
target = df['salary_more_then_100k']

inputs

target

from sklearn.preprocessing import LabelEncoder

le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree = LabelEncoder()

inputs['company_n']  = le_company.fit_transform(inputs['company'])
inputs['job_n']  = le_job.fit_transform(inputs['job'])
inputs['degree_n']  = le_degree.fit_transform(inputs['degree'])

inputs.head()

inputs_n = inputs.drop(['company','job','degree'],axis='columns')
inputs_n

from sklearn import tree

model = tree.DecisionTreeClassifier()

model.fit(inputs_n,target)

model.score(inputs_n,target)

model.predict